version: '3.8'

services:
  # Flask backend service
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app
      - ./backend/feedback.db:/app/db/feedback.db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    ports:
      - "5000:5000"
    networks:
      - app_network

  # Next.js frontend service
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXT_PUBLIC_API_URL=http://backend:5000
      - NEXTAUTH_SECRET="mGgh1kMZRp+cdsOmI1mIJpC+20kHZIeLogoGCj5Z/YY="
    ports:
      - "3000:3000"
    networks:
      - app_network


networks:
  app_network:
    driver: bridge
